# Generated by Django 3.0.5 on 2020-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('n_vertices', models.IntegerField()),
                ('n_aristas', models.IntegerField()),
                ('vertices_labels', models.CharField(max_length=100000)),
                ('aristas_de', models.CharField(max_length=100000)),
                ('aristas_hasta', models.CharField(max_length=100000)),
                ('pesos', models.CharField(max_length=100000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
